//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: hashish.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifdef __GNUG__
    #pragma implementation "hashish_wdr.cpp"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "hashish_wdr.h"


// Implement window functions

wxSizer *MainDiag( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxFlexGridSizer *item0 = new wxFlexGridSizer( 2, 0, 0 );
    item0->AddGrowableCol( 1 );

    wxFlexGridSizer *item1 = new wxFlexGridSizer( 1, 0, 0 );

    wxString strs2[] = 
    {
        "File", 
        "String"
    };
    wxRadioBox *item2 = new wxRadioBox( parent, ID_HASH_SOURCE, "Source", wxDefaultPosition, wxDefaultSize, 2, strs2, 1, wxRA_SPECIFY_COLS );
    item1->Add( item2, 0, wxALIGN_CENTRE|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTRE|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    wxFlexGridSizer *item3 = new wxFlexGridSizer( 1, 0, 0 );
    item3->AddGrowableCol( 0 );

    wxFlexGridSizer *item4 = new wxFlexGridSizer( 2, 0, 0 );
    item4->AddGrowableCol( 0 );

    wxTextCtrl *item5 = new wxTextCtrl( parent, ID_FILE_NAME, "", wxDefaultPosition, wxSize(180,-1), 0 );
    item4->Add( item5, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxRIGHT|wxTOP|wxBOTTOM, 5 );

    wxButton *item6 = new wxButton( parent, ID_BUTTON_BROWSE, "Browse", wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item6, 0, wxALIGN_CENTRE|wxALL, 5 );

    item3->Add( item4, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 0 );

    wxFlexGridSizer *item7 = new wxFlexGridSizer( 1, 0, 0 );
    item7->AddGrowableCol( 0 );

    wxTextCtrl *item8 = new wxTextCtrl( parent, ID_STRING, "", wxDefaultPosition, wxSize(80,-1), 0 );
    item8->Enable( FALSE );
    item7->Add( item8, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 );

    item3->Add( item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 );

    item0->Add( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxLEFT|wxRIGHT|wxTOP, 5 );

    item0->Add( 20, 20, 0, wxALIGN_CENTRE, 5 );

    wxFlexGridSizer *item9 = new wxFlexGridSizer( 2, 0, 0 );
    item9->AddGrowableCol( 1 );

    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT, "Algorithm", wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxString strs11[] = 
    {
        "SHA-1", 
        "SHA-256", 
        "SHA-384", 
        "SHA-512", 
        "MD2", 
        "MD5", 
        "HAVAL", 
        "HAVAL-3", 
        "HAVAL-4", 
        "HAVAL-5", 
        "RIPEMD-160", 
        "Tiger", 
        "Panama Hash", 
        "CRC-32", 
        "Sapphire Hash"
    };
    wxChoice *item11 = new wxChoice( parent, ID_LIST_HASH, wxDefaultPosition, wxSize(130,-1), 15, strs11, 0 );
    item9->Add( item11, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item0->Add( item9, 0, wxALIGN_CENTRE, 5 );

    wxButton *item12 = new wxButton( parent, ID_HASH, "Hash", wxDefaultPosition, wxDefaultSize, 0 );
    item12->SetDefault();
    item0->Add( item12, 0, wxALIGN_CENTRE|wxALL, 5 );

    wxTextCtrl *item13 = new wxTextCtrl( parent, ID_HASHOUT, "", wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item0->Add( item13, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    
    return item0;
}

// Implement menubar functions

wxMenuBar *MainMenu()
{
    wxMenuBar *item0 = new wxMenuBar;
    
    wxMenu* item1 = new wxMenu;
    item1->Append( ID_MENU_OPEN, "Open File", "" );
    item1->AppendSeparator();
    item1->Append( ID_MENU_QUIT, "Quit", "" );
    item0->Append( item1, "File" );
    
    wxMenu* item2 = new wxMenu;
    item2->Append( ID_MENU_HEX, "Hex (Base 16)", "", TRUE );
    item2->Append( ID_MENU_64, "Base 64", "", TRUE );
    item0->Append( item2, "Encoding" );
    
    wxMenu* item3 = new wxMenu;
    item3->Append( ID_MENU_ABOUT, "About Hashish", "" );
    item0->Append( item3, "About" );
    
    return item0;
}

// Implement toolbar functions

// Implement bitmap functions


// End of generated file
