//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: hashish.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_hashish_H__
#define __WDR_hashish_H__

#ifdef __GNUG__
    #pragma interface "hashish_wdr.cpp"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_HASH_SOURCE 10000
#define ID_FILE_NAME 10001
#define ID_BUTTON_BROWSE 10002
#define ID_STRING 10003
#define ID_TEXT 10004
#define ID_LIST_HASH 10005
#define ID_HASH 10006
#define ID_HASHOUT 10007
wxSizer *MainDiag( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

#define ID_MENU 10008
#define ID_MENU_OPEN 10009
#define ID_MENU_QUIT 10010
#define ID_MENU_HEX 10011
#define ID_MENU_64 10012
#define ID_MENU_ABOUT 10013
wxMenuBar *MainMenu();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
